<a href="https://colab.research.google.com/github/sukh-coder30/Function/blob/main/Assignment_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np


In [ ]:
arr = np.random.randint(1, 101, (3, 3))

In [ ]:
arr

array([[18,  1, 77],
       [22, 44, 31],
       [41, 41, 36]])

In [ ]:
Transposed_arr = arr.T
print("\nTransposed Array:")
print(Transposed_arr)


Transposed Array:
[[18 22 41]
 [ 1 44 41]
 [77 31 36]]


Q2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
arr1 = np.random.rand(10)

In [5]:
arr1

array([0.03722985, 0.25980901, 0.78650409, 0.08673294, 0.30601691,
       0.65977299, 0.01014099, 0.99552176, 0.42080545, 0.33209044])

In [6]:
np.reshape(arr1,(2, 5) )

array([[0.03722985, 0.25980901, 0.78650409, 0.08673294, 0.30601691],
       [0.65977299, 0.01014099, 0.99552176, 0.42080545, 0.33209044]])

In [7]:
np.reshape(arr1,(5, 2) )

array([[0.03722985, 0.25980901],
       [0.78650409, 0.08673294],
       [0.30601691, 0.65977299],
       [0.01014099, 0.99552176],
       [0.42080545, 0.33209044]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.



In [21]:
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(padded_arr)

Original 4x4 Array:
[[0.72481353 0.97132334 0.16108459 0.79514043]
 [0.31246162 0.4865634  0.88753364 0.42178613]
 [0.29796715 0.69741429 0.40996767 0.13997979]
 [0.66495805 0.26978458 0.17120037 0.68927723]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.72481353 0.97132334 0.16108459 0.79514043 0.        ]
 [0.         0.31246162 0.4865634  0.88753364 0.42178613 0.        ]
 [0.         0.29796715 0.69741429 0.40996767 0.13997979 0.        ]
 [0.         0.66495805 0.26978458 0.17120037 0.68927723 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [22]:

arr = np.arange(10, 65, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element

In [23]:
arr = np.array(['python', 'numpy', 'pandas'])

uppercase_arr = np.char.upper(arr)

lowercase_arr = np.char.lower(arr)

titlecase_arr = np.char.title(arr)

print("Original Array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title Case:", titlecase_arr)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


 5. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [24]:
arr = np.array(['python', 'numpy', 'pandas'])

spaced_arr = np.char.join(' ', arr)

print("Original Array:", arr)
print("Spaced Array:", spaced_arr)

Original Array: ['python' 'numpy' 'pandas']
Spaced Array: ['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

addition = np.add(arr1, arr2)
subtraction = np.subtract(arr1, arr2)
multiplication = np.multiply(arr1, arr2)
division = np.divide(arr1, arr2)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

print("\nElement-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [26]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [27]:
random_array = np.random.randint(0, 1000, size=100)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in random_array if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Prime Numbers in the Array:
[907, 613, 683, 317, 349, 97, 739, 617, 863, 751, 751, 643, 229, 431, 109]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [30]:
np.random.seed(42)

temperatures = np.random.uniform(15, 30, 30)

print("Daily temperatures for the month:")
print(temperatures)
print("\Shape of the array:", temperatures.shape)

weekly_temps = temperatures[:28].reshape(4, 7)

weekly_averages = np.mean(weekly_temps, axis=1)

print("Weekly averages:")
for week, avg in enumerate(weekly_averages, 1):
    print(f"Week {week}: {avg:.2f}\u00b0C")


Daily temperatures for the month:
[20.61810178 29.2607146  25.97990913 23.97987726 17.34027961 17.33991781
 15.87125418 27.99264219 24.01672518 25.62108867 15.30876741 29.54864778
 27.48663961 18.18508666 17.72737451 17.75106765 19.56363364 22.87134647
 21.47917528 19.3684371  24.17779342 17.09240791 19.38216973 20.49542765
 21.84104976 26.77763942 17.99510673 22.71351658 23.88621853 15.69675619]
Shape of the array: (30,)
Weekly averages:
Week 1: 21.48°C
Week 2: 24.02°C
Week 3: 20.42°C
Week 4: 20.90°C
