In [1]:
#Numpy>> Numerical Python
#developed 2005 by Travis Oliphant
#import numpy as np
#np._version_
#NUMPY STORE ARRAY IN HOMOGENOUSE ARRAY MATHMATICAL COMPUTATION FAST is imports c language that's why python is fastest progarmming language

#mathematics Tool
#matlab
#lingo
#tora
#Spss


In [3]:
import numpy as np


In [5]:
a = np.array([1, 2,3 ,4])
type(a)

numpy.ndarray

In [6]:
p = np.array([[1,2,3], [1,2,3]])

type(p)

numpy.ndarray

In [8]:
p

array([[1, 2, 3],
       [1, 2, 3]])

In [9]:
#matrix is a specialized  2d array

In [10]:
l = [1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [12]:
t = (1, 2, 3, True)

In [11]:
np.array(l)

array([1, 2, 3, 4, 5])

In [13]:
np.array(t)

array([1, 2, 3, 1])

In [14]:
s = {"ram":500, "shyam":300}

In [15]:
np.array(s)

array({'ram': 500, 'shyam': 300}, dtype=object)

In [16]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
#make an array from any tuple iterables

iterator = (i for i in range(5))
np.fromiter(iterator, float)

array([0., 1., 2., 3., 4.])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(1, 15, 10)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [25]:
a = np.zeros(5)
a.ndim

1

In [26]:
s= np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
s = np.ones((3, 4))
s.ndim

2

In [37]:
s = np.zeros((1,3, 4))
s.shape

(1, 3, 4)

In [39]:
s= np.ones((3,4))
s+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [40]:
s= np.ones((3,4))
s*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [42]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [43]:
np.random.random_sample()

0.4548556467365592

In [44]:
np.random.random_sample((5, ))

array([0.88140219, 0.13235412, 0.46090732, 0.55748608, 0.66508104])

In [45]:
np.random.rand(2,3)

array([[0.59398003, 0.05542739, 0.2874116 ],
       [0.4407382 , 0.14965994, 0.7000018 ]])

In [47]:
arr = np.random.randint(1, 5, size = (3, 4))

array([[4, 2, 3, 3],
       [4, 2, 3, 1],
       [2, 4, 4, 3]])

In [50]:
arr = np.random.randint(1, 5, size = (3, 4))
arr.reshape(12, 1)

array([[3],
       [3],
       [1],
       [2],
       [4],
       [2],
       [3],
       [4],
       [1],
       [4],
       [1],
       [3]])

In [51]:
arr.reshape(-1, 2)

array([[3, 3],
       [1, 2],
       [4, 2],
       [3, 4],
       [1, 4],
       [1, 3]])

In [52]:
arr.size

12

In [54]:
arr = np.random.randint(1, 5, size = (3, 4))
arr[0:2, [0]]

array([[4],
       [3]])

In [55]:
arr[0:2, 0:2]

array([[4, 1],
       [3, 1]])

In [56]:
arr1 = np.random.randint(1, 5, size = (3, 4))
arr  = np.random.randint(1, 5, size = (3, 4))

In [58]:
arr1+arr

array([[8, 3, 5, 5],
       [5, 2, 4, 3],
       [5, 4, 5, 6]])

In [60]:
arr1 = np.random.randint(1, 5, size = (3, 3))
arr  = np.random.randint(1, 5, size = (3, 3))
arr1 @ arr

array([[27, 24, 30],
       [15, 12, 16],
       [16, 12, 16]])

In [61]:
arr1 = np.random.randint(1, 5, size = (3, 3))

In [62]:
arr.T

array([[4, 2, 3],
       [2, 4, 2],
       [3, 4, 3]])

In [63]:
arr1 = np.random.randint(1, 5, size = (3, 3))

In [64]:
arr1.flatten()

array([3, 3, 1, 4, 1, 1, 1, 1, 3])

In [69]:
#expand dimension
arr1 = np.random.randint(1, 5, size = (3, 3))
np.expand_dims(arr1, axis = 1)

array([[[1, 1, 2]],

       [[3, 1, 1]],

       [[2, 1, 4]]])

In [71]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [72]:
b = np.array([16, 8, 0])
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])